services:
  - type: web
    name: best-electronics
    env: php
    plan: free
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    rootDir: .
